version: '2.2'
services:
    management-db:
        image: mysql:8.0.20
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: Management
        ports:
            - 3306:3306
        volumes:
            - ./Data/DB:/var/lib/mysql
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.3
    # frontend:
    #     build: ./FrontEnd/.
    #     ports:
    #         - 80:80
    #     networks:
    #         - RyukokuBooksSystem
    management-api:
        build: ./ManagementApiServer/.
        ports:
            - 80:80
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.4

networks:
    RyukokuBooksSystem:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.0.1.0/24