version: '2.2'
services:
    proxy:
        build: ./Proxy/.
        ports:
            - 80:80
            - 443:443
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.6
    file:
        build: ./FileServer/.
        volumes:
            - ./Data/Qrcode:/opt/Qrcode
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.7
    management-db:
        image: mysql:8.0.20
        environment:
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_DATABASE: Management
        volumes:
            - ./Data/DB:/var/lib/mysql
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.3
    frontend:
        build: ./FrontEnd/.
        networks:
            - RyukokuBooksSystem
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.4
    management-api:
        build: ./ManagementApiServer_ts/.
        volumes:
            - ./Data/Qrcode:/home/ManagementAPI/Qrcode
        networks:
            RyukokuBooksSystem:
                ipv4_address: 172.0.1.5

networks:
    RyukokuBooksSystem:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.0.1.0/24